[scene]
width = 800
height = 800
background = "#0a0a1a"

[phyllotaxis]
spacing_constant = 10.0
# Which Fibonacci number to use for spiral families (1=1, 2=1, 3=2, 4=3, 5=5, 6=8, 7=13, 8=21)
spiral_fib_index = 7
seeds_per_arm = 20


[animation]
total_frames = 450
framerate = 30
# Fractions of total timeline, must sum to 1.0
appear_ratio = 0.40
reveal_ratio = 0.45
hold_ratio = 0.15

[style]
neutral_color = "#555566"
color_1 = "#FDBE02"
color_2 = "#AA0000"
seed_radius = 5.0
opacity = 0.9

[camera]
start_scale = 1.4
end_scale = 1.0
padding = 1.3

[export]
output_dir = "output/"
filename = "phyllotaxis"
converter = "playwright_http"
png_width_px = 1600
